export enum AuditStatus {
  GREEN = 'GREEN',
  AMBER = 'AMBER',
  RED = 'RED'
}

export enum AgentStatus {
  IDLE = 'IDLE',
  FETCHING_DATA = 'FETCHING_DATA',
  CALCULATING_SCORES = 'CALCULATING_SCORES',
  ANALYZING_GAPS = 'ANALYZING_GAPS', // Gemini
  GENERATING_PLAN = 'GENERATING_PLAN', // Gemini
  COMPLETED = 'COMPLETED',
  ERROR = 'ERROR'
}

export interface MaterialStats {
  total: number;
  compliant: number;
  expired: number;
  nonCompliant: number;
}

export interface MenuStats {
  total: number;
  compliant: number;
  partial: number;
  nonCompliant: number;
}

export interface DocumentCategory {
  id: string;
  name: string;
  required: number;
  approved: number;
}

export interface AlertStats {
  total: number;
  high: number;
  medium: number;
  low: number;
}

export interface ComponentScore {
  name: string;
  score: number;
  weight: number;
  contribution: number;
  details: any;
}

export interface OutletScoreResult {
  outletId: number;
  outletName: string;
  overallScore: number;
  status: AuditStatus;
  goalMet: boolean;
  components: {
    material: ComponentScore;
    menu: ComponentScore;
    documentation: ComponentScore;
    alerts: ComponentScore;
  };
  // Generated by Gemini
  gapsIdentified?: string[];
  improvementPlan?: string;
  nextReviewDate?: string;
  scoredAt: string;
}

// Mock DB Entities
export interface Outlet {
  id: number;
  name: string;
  location: string;
  lastScore?: number;
  lastStatus?: AuditStatus;
}

export interface RawMaterial {
  id: number;
  name: string;
  status: 'SAFE' | 'WARNING' | 'EXPIRED' | 'NON_COMPLIANT';
}

export interface Menu {
  id: number;
  name: string;
  status: 'COMPLIANT' | 'PARTIALLY_COMPLIANT' | 'NON_COMPLIANT';
  isActive: boolean;
}

export interface Alert {
  id: number;
  message: string;
  severity: 'HIGH' | 'MEDIUM' | 'LOW';
  status: 'ACTIVE' | 'RESOLVED';
}
